# Generated by Django 4.1 on 2024-11-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=100)),
                (
                    "accreditation_file",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("accreditation_status", models.BooleanField(default=False)),
                ("register_date", models.DateField(blank=True, null=True)),
                ("status", models.BooleanField()),
            ],
        ),
    ]
