# Generated by Django 4.1 on 2024-11-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_shelter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="accreditation_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/",
                verbose_name="Documento acreditativo",
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="accreditation_status",
            field=models.BooleanField(
                default=True, verbose_name="Estado de acreditación"
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Correo electrónico"),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="register_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de registro"
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="status",
            field=models.BooleanField(blank=True, null=True, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="telephone",
            field=models.CharField(max_length=12, verbose_name="Teléfono"),
        ),
    ]
