# Generated by Django 5.1.3 on 2024-11-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_adoptionapplication_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncuestaAdopcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cuidados",
                    models.CharField(
                        help_text="¿Cómo planeas cuidar al animal?", max_length=255
                    ),
                ),
                (
                    "experiencia_previa",
                    models.TextField(
                        help_text="¿Tienes experiencia previa en el cuidado de animales?"
                    ),
                ),
                (
                    "tiempo_atencion",
                    models.CharField(
                        choices=[
                            ("Poco", "Poco"),
                            ("Moderado", "Moderado"),
                            ("Mucho", "Mucho"),
                        ],
                        help_text="¿Cuánto tiempo puedes dedicar a cuidar al animal?",
                        max_length=100,
                    ),
                ),
                (
                    "tipo_vivienda",
                    models.CharField(
                        choices=[("Casa", "Casa"), ("Apartamento", "Apartamento")],
                        help_text="¿En qué tipo de vivienda vives?",
                        max_length=100,
                    ),
                ),
                (
                    "otras_observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Otras observaciones sobre tu capacidad para cuidar al animal.",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="adoptionapplication",
            name="status",
            field=models.CharField(
                choices=[("P", "Pendiente"), ("A", "Aprobada"), ("D", "Denegada")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="RespuestaEncuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuidados_respuesta", models.CharField(max_length=255)),
                ("experiencia_respuesta", models.TextField()),
                ("tiempo_respuesta", models.CharField(max_length=100)),
                ("vivienda_respuesta", models.CharField(max_length=100)),
                ("otras_observaciones_respuesta", models.TextField(blank=True)),
                (
                    "encuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.encuestaadopcion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
