# Generated by Django 5.1.3 on 2024-12-05 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_questions_test_answers"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompatibilityTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pet_type",
                    models.CharField(
                        choices=[("dog", "Perro"), ("cat", "Gato")], max_length=3
                    ),
                ),
                ("dog_age_preference", models.CharField(max_length=20)),
                ("dog_coat_type", models.CharField(max_length=20)),
                ("dog_character", models.CharField(max_length=20)),
                ("dog_energy_level", models.CharField(max_length=20)),
                ("dog_other_pets", models.CharField(max_length=20)),
                ("cat_age_preference", models.CharField(max_length=20)),
                ("cat_coat_type", models.CharField(max_length=20)),
                ("cat_character", models.CharField(max_length=20)),
                ("cat_energy_level", models.CharField(max_length=20)),
                ("cat_other_pets", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
