# Generated by Django 5.1.3 on 2024-12-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_intent_patterns_remove_intent_responses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="response_text",
            field=models.TextField(),
        ),
    ]
