# Generated by Django 5.1.3 on 2024-12-03 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_response_response_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intent",
            name="description",
        ),
        migrations.AddField(
            model_name="intent",
            name="patterns",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="intent",
            name="responses",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="intent",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Response",
        ),
    ]
