# Generated by Django 5.1.3 on 2024-12-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_intent_description_intent_patterns_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intent",
            name="patterns",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="intent",
            name="responses",
            field=models.JSONField(default=list),
        ),
    ]
