# Generated by Django 4.1 on 2024-11-30 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("shelters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptionapplication",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.shelterworkerprofile",
            ),
        ),
    ]
