# Generated by Django 5.1.3 on 2024-12-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="adoption_status",
            field=models.CharField(
                choices=[
                    ("disponible", "Disponible"),
                    ("reservado", "Reservado"),
                    ("adoptado", "Adoptado"),
                ],
                default="Disponible",
                max_length=10,
            ),
        ),
    ]
