# Generated by Django 5.1.4 on 2024-12-14 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0002_event_shelter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="shelter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="shelters.shelter",
            ),
        ),
    ]
