# Generated by Django 5.1.3 on 2024-11-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptionapplication",
            name="shelter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shelters.shelter",
            ),
        ),
    ]
