# Generated by Django 5.1.3 on 2024-12-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0003_alter_animal_adoption_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="sex",
            field=models.CharField(
                choices=[("macho", "Macho"), ("hembra", "Hembra")],
                default="Macho",
                max_length=10,
            ),
        ),
    ]
