# Generated by Django 5.1.3 on 2024-12-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0003_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("alimentos", "Alimentos"),
                    ("medicamentos_vacunas", "Medicamentos y Vacunas"),
                    ("otros", "Otros"),
                ],
                default=2,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="expiration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de caducidad"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="no_expiration",
            field=models.BooleanField(
                default=False, verbose_name="Sin fecha de caducidad"
            ),
        ),
    ]
