# Generated by Django 5.1.3 on 2024-11-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0003_adoptionapplication_shelter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="telephone",
            field=models.CharField(max_length=9, verbose_name="Teléfono"),
        ),
    ]
