# Generated by Django 5.1.4 on 2024-12-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0003_alter_event_shelter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="shelter",
        ),
    ]
