# Generated by Django 5.1.2 on 2024-11-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0004_alter_shelter_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelter",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitud"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitud"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Código Postal"
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="telephone",
            field=models.CharField(max_length=12, verbose_name="Teléfono"),
        ),
    ]
