# Generated by Django 5.1.4 on 2024-12-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0004_remove_event_shelter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="user",
        ),
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
