# Generated by Django 4.1 on 2024-11-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0004_shelter_latitude_shelter_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelter",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Código Postal"
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitud"),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitud"),
        ),
    ]
