# Generated by Django 5.1.3 on 2024-12-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0004_animal_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="features",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
