# Generated by Django 5.1.3 on 2024-12-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0004_item_category_item_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("alimentos", "Alimentos"),
                    ("medicamentos_vacunas", "Medicamentos y Vacunas"),
                    ("otros", "Otros"),
                ],
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
    ]
