# Generated by Django 5.1.3 on 2024-12-04 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0005_shelter_latitude_shelter_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="energy",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("moderado", "Moderado"),
                    ("tranquilo", "Tranquilo"),
                ],
                default="Activo",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="features",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="fur",
            field=models.CharField(
                choices=[("largo", "Largo"), ("corto", "Corto")],
                default="Corto",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="personality",
            field=models.CharField(
                choices=[
                    ("sociable", "Sociable"),
                    ("protector", "Protector"),
                    ("independiente", "Independiente"),
                ],
                default="Sociable",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="sex",
            field=models.CharField(
                choices=[("macho", "Macho"), ("hembra", "Hembra")],
                default="Macho",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="shelter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="shelters.shelter",
                verbose_name="Protectora",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="size",
            field=models.CharField(
                choices=[
                    ("grande", "Grande"),
                    ("mediano", "Mediano"),
                    ("pequeño", "Pequeño"),
                ],
                default="Grande",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="adoption_status",
            field=models.CharField(
                choices=[
                    ("disponible", "Disponible"),
                    ("reservado", "Reservado"),
                    ("adoptado", "Adoptado"),
                ],
                default="Disponible",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
    ]
