# Generated by Django 5.1.3 on 2024-12-04 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0006_animal_energy_animal_features_animal_fur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="shelter",
            field=models.ForeignKey(
                default="No tiene",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="shelters.shelter",
                verbose_name="Protectora",
            ),
        ),
    ]
