# Generated by Django 5.1.3 on 2024-12-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0007_alter_animal_shelter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="shelter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="shelters.shelter",
                verbose_name="Protectora",
            ),
        ),
    ]
