# Generated by Django 5.1.3 on 2024-12-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0009_alter_animal_shelter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="energy",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("moderado", "Moderado"),
                    ("tranquilo", "Tranquilo"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="fur",
            field=models.CharField(
                choices=[("largo", "Largo"), ("corto", "Corto")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="personality",
            field=models.CharField(
                choices=[
                    ("sociable", "Sociable"),
                    ("protector", "Protector"),
                    ("independiente", "Independiente"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="size",
            field=models.CharField(
                choices=[
                    ("grande", "Grande"),
                    ("mediano", "Mediano"),
                    ("pequeño", "Pequeño"),
                ],
                max_length=10,
            ),
        ),
    ]
